version: '3.8'

services:
  app:
    image: ghcr.io/raihanathallah/express-api:latest
    container_name: raihan-portofolio-api-express
    restart: always # Ensures the container restarts on failure
    working_dir: /app
    env_file:
      - .env # Use a local .env file for environment variables
    ports:
      - "8090:8090"
    command: ["node", "dist/index.js"]
